### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by kristofferSohagenUiA** [p-rott/b.ad-Motorcontroller#1]
Hi, can you explain how you managed to connect the controller to Arduino IDE? Thanks!

**Comment by p-rott** [comment]
I'm assuming you mean the STEVAL-GMBL01V1? Sure, take a look at the datasheet/reference if you haven't yet:
https://www.st.com/resource/en/user_manual/um2460-reference-design-kit-for-gimbal-controller-for-drones-and-handheld-applications-stmicroelectronics.pdf

Read chapters 2.3, 2.8 and 3.1.
You'll either need a STLink of some kind (like a cheap ebay clone STLink v3), or use a STM32 Nucleo-64 board with the header.

You'll also need to install the STM32Duino addin for your Arduino IDE, see here:
https://github.com/stm32duino/Arduino_Core_STM32

Good luck!

Edit: Also check out the forums for the SimpleFOC library, very nice and knowledgeable people there: community.simplefoc.com

**Comment by kristofferSohagenUiA** [comment]
Thank you!

**Comment by p-rott** [comment]
You're quite welcome! Let me know if you run into further issues or questions.
